### should return HttpStatus 201 and info: Order Placed Successfully
POST http://localhost:8080/api/order
Content-Type: application/json

{
  "orderLineItemsDtoList": [
    {
      "skuCode": "iPhone",
      "price": 1000,
      "quantity": 1
    }
  ]
}

### should throw excepotion
POST http://localhost:8080/api/order
Content-Type: application/json

{
  "orderLineItemsDtoList": [
    {
      "skuCode": "iPhone",
      "price": 1000,
      "quantity": 1
    },
    {
      "skuCode": "iPhone_13",
      "price": 1000,
      "quantity": 1
    }
  ]
}